vich_uploader:
    db_driver: orm

    mappings:
        subjects:
            uri_prefix: '%app.path.subjects%'
            upload_destination: '%kernel.project_dir%/public/uploads/subjects/'
            namer: vich_uploader.namer_uniqid

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
